return {
	"\nOriginally developed and published by ZeptoLab.\n\nA Cut the Rope Home fan project.",
	"\nProject lead:\nyell0wsuit\n",
	"Cut the Rope Home team members:\n",
	"8 Second Rocket\naidrum\nBingies24\ncv\nGenji\nMlopsFunny\nMrCatz\nsaulfabreg\nTheAwesomeBlue\nyell0wsuit\n\n",
	"Cut the Rope PC version. Copyright 2012 by ZeptoLab.\n\nAdditional Design:\nNataliya Omelyanchuk\n\nMusic and Sounds:\nAlexander Falinski",
	"Quality assurance:\nSPL\nUniversally Speaking\n\nSpecial Thanks:\nVladimir Agafonov, Maks Chekmarev, Dmitry Chernenko, Alexander Danilov, Alexandra Dubovitskaya, Grigory Kireev, Viktor Kuzmin, Louise Lazzari, Brandyn Rasmussen, Tiago Amorim Rocha, Andrey Vengerskiy, Barbos, Uliya Voinova, Elena Volk\n\nVery Special Thanks: 1C Wireless\n\n(c) ZeptoLab UK Ltd.  All rights reserved. ZeptoLab, Cut the Rope, Om Nom and Feed with Candy are the trademarks of ZeptoLab.\n\nLegal: Hughes Media Law Group",
}

