#include "interface.hpp"
#include "level.hpp"
#include "menuassets.hpp"
#include "result.hpp"
#include <cassert>
#include <cstdio>

int main() {
    dx::simulation game;
    game.reset(dx::firstlevel);
    ui::controller menu;
    auto pen = [&](int x, int y, bool held) { menu.update(game, {x, y, 0, held}); };
    auto tap = [&](int x, int y) { pen(x, y, true); pen(x, y, false); pen(x, y, false); };
    auto key = [&](int value) { menu.update(game, {0, 0, value, false}); };
    auto settle = [&]() { for (int i = 0; i < 40 && menu.blocked(); ++i) menu.advance(game); assert(!menu.blocked()); };
    assert(menu.mode == ui::view::home);
    key(ui::accept);
    assert(menu.mode == ui::view::packs);
    key(ui::accept);
    assert(menu.mode == ui::view::levels);
    key(ui::accept);
    assert(menu.mode == ui::view::playing && menu.reset);
    key(ui::start);
    assert(menu.mode == ui::view::playing && menu.door == 1);
    settle();
    pen(241, 8, true);
    pen(100, 40, true);
    assert(!menu.gameTouch && menu.pressed == -1);
    pen(100, 40, false);
    assert(menu.mode == ui::view::playing);
    pen(100, 40, true);
    assert(menu.gameTouch);
    key(ui::start);
    assert(menu.mode == ui::view::paused && !menu.gameTouch);
    pen(128, 47, true);
    assert(menu.mode == ui::view::paused);
    pen(128, 47, false);
    assert(menu.mode == ui::view::playing && !menu.gameTouch);
    tap(241, 8);
    assert(menu.mode == ui::view::paused);
    tap(128, 72);
    assert(menu.mode == ui::view::paused && !menu.reset);
    tap(104, 145);
    tap(152, 145);
    assert(!menu.effects && !menu.music);
    key(ui::following);
    assert(menu.focus == 0);
    key(ui::following);
    assert(menu.focus == 2);
    key(ui::accept);
    assert(menu.door == 2 && menu.mode == ui::view::paused);
    settle();
    assert(menu.mode == ui::view::levels);
    key(ui::cancel);
    assert(menu.mode == ui::view::packs);
    key(ui::cancel);
    assert(menu.mode == ui::view::home);
    key(ui::accept);
    assert(menu.mode == ui::view::packs);
    key(ui::accept);
    assert(menu.mode == ui::view::levels);
    key(ui::accept);
    assert(menu.mode == ui::view::playing && menu.reset && !menu.effects && !menu.music);
    settle();
    menu.update(game, {});
    assert(!menu.reset);
    game.state = dx::outcome::won;
    game.resulttick = 500;
    game.count = 3;
    game.stars = {true, true, true};
    for (int i = 0; i < 124; ++i) menu.advance(game);
    assert(menu.mode == ui::view::playing);
    menu.advance(game);
    assert(menu.mode == ui::view::results && menu.score == 5200 && menu.bestscore == 5200 && menu.beststars == 3);
    assert(!menu.improved);
    key(ui::accept);
    assert(menu.mode == ui::view::results);
    settle();
    assert(menu.hasnext() && menu.levelopen(1) && !menu.levelopen(2));
    key(ui::following);
    assert(menu.focus == 1);
    key(ui::previous);
    assert(menu.focus == 0);
    key(ui::accept);
    assert(menu.reset && menu.mode == ui::view::playing && menu.starage[0] == -1 && menu.bestscore == 5200);
    assert(menu.replaypanel && menu.door == 1);
    settle();
    game.reset(dx::firstlevel);
    game.state = dx::outcome::lost;
    menu.update(game, {});
    for (int i = 0; i < 62; ++i) menu.advance(game);
    assert(menu.mode == ui::view::playing && !menu.flash && !menu.reset);
    menu.advance(game);
    assert(menu.flash == 1 && menu.bestscore == 5200 && !menu.reset);
    for (int i = 0; i < 9; ++i) { menu.update(game, {}); menu.advance(game); assert(!menu.reset); }
    menu.advance(game);
    assert(menu.reset && menu.flash == 2 && menu.white() == 1);
    game.reset(dx::firstlevel);
    settle();
    assert(menu.mode == ui::view::playing && menu.white() == 0);
    key(ui::cancel);
    tap(128, 96);
    settle();
    assert(menu.mode == ui::view::levels);
    key(ui::cancel);
    key(ui::cancel);
    tap(128, 170);
    assert(menu.mode == ui::view::options);
    tap(128, 77);
    assert(menu.mode == ui::view::resetmenu && menu.bestscore == 5200);
    tap(128, 138);
    assert(menu.mode == ui::view::options && menu.bestscore == 5200);
    tap(128, 77);
    tap(128, 108);
    assert(menu.mode == ui::view::options && menu.bestscore == 0 && menu.beststars == 0);
    tap(148, 150);
    assert(menu.clickcut);
    tap(128, 53);
    tap(128, 59);
    assert(menu.mode == ui::view::languages && menu.locale == 1);
    key(ui::cancel);
    tap(128, 102);
    assert(menu.mode == ui::view::credits);
    for (int i = 0; i < 60; ++i) menu.advance(game);
    assert(menu.creditoffset > 3);
    pen(128, 150, true);
    pen(128, 50, true);
    pen(128, 50, false);
    assert(!menu.autoscroll && menu.creditoffset > 90);
    ui::scroller strip;
    strip.moveto(1);
    strip.update(.016f);
    assert(std::abs(strip.x + 32.768f) < .0001f);
    for (int i = 0; i < 300; ++i) strip.update(.016f);
    assert(!strip.moving && strip.x == -640);
    strip.begin(0);
    strip.drag(700);
    assert(strip.x == -640 && strip.release());
    strip.begin(0);
    strip.drag(-200);
    strip.update(.016f);
    assert(!strip.release() && strip.selected == 2);
    assert(ui::controller::points(3, 0) == 6000);
    assert(ui::controller::points(2, 2000) == 2000);
    assert(ui::controller::points(0, 1875) == 0);
    assert(ui::resultat(.5f, 3, 5200, 500).scorealpha == 0);
    const auto stars = ui::resultat(1.5f, 3, 5200, 500);
    assert(stars.row == 0 && stars.score == 1500 && stars.value == 1500);
    const auto time = ui::resultat(2.9f, 3, 5200, 500);
    assert(time.row == 1 && std::abs(time.score - 4100) <= 1 && time.value == 4);
    assert(ui::resultat(3.8f, 3, 5200, 500).score == 5200);
    ui::controller progression;
    assert(!progression.packopen(1));
    for (int i = 0; i < 10; ++i) progression.saves.complete(i, 5000, 3);
    assert(progression.packopen(1) && !progression.packopen(2) && progression.totalstars() == 30);
    progression.pack = 1;
    assert(progression.levelopen(0) && !progression.levelopen(1));
    progression.saves.complete(25, 0, 0);
    assert(progression.levelopen(1));
    progression.mode = ui::view::results; progression.age = 100;
    progression.update(game, {158,125,0,true});
    progression.update(game, {158,125,0,false});
    assert(progression.level == 1 && progression.levelid() == 26 && progression.reset);
    progression.pack = 1; progression.level = 24;
    assert(!progression.hasnext());
    progression.saves.toggle();
    assert(progression.hasnext());
    progression.pack = 5; progression.level = 24; assert(progression.hasnext());
    progression.pack = 7; progression.level = 24; assert(progression.hasnext());
    progression.pack = menuart::playableboxes - 1; progression.level = 24; assert(!progression.hasnext());
    int previous = 0;
    for (int i = 0; i < 360; ++i) {
        const auto state = ui::resultat(i * .016f, 3, 5200, 500);
        assert(state.score >= previous && state.score <= 5200 && state.alpha >= 0 && state.alpha <= 1);
        previous = state.score;
    }
    // Exercise a press/release across every win-delay/result-opening boundary.
    for (int age = 0; age < 160; ++age) for (int control = 0; control < 2; ++control) {
        ui::controller race;
        race.mode = ui::view::playing;
        game.state = dx::outcome::won;
        for (int i = 0; i < age; ++i) race.advance(game);
        const int x = control ? menuart::hudpositions[0][0] : menuart::hudpositions[0][2];
        race.update(game, {x, 8, 0, true});
        race.advance(game);
        race.update(game, {x, 8, 0, false});
        if (race.mode == ui::view::paused) race.update(game, {0,0,ui::start,false});
        int resets = 0;
        for (int i = 0; i < 240; ++i) {
            race.update(game, {});
            race.advance(game);
            if (race.reset) { ++resets; game.reset(dx::firstlevel); }
        }
        assert(!race.blocked() && resets <= 1);
        assert(race.mode == ui::view::results || (race.mode == ui::view::playing && game.state == dx::outcome::playing));
    }
    std::puts("PASS: UI capture/cancel, pause/resume, audio, frontend, localization, persistence, DX scrolling, two-second win, delayed white retry, 320 transition-input boundaries, scoring");
}
