name: Build Ports

on:
    push:
        branches: [main]

permissions:
    contents: read

concurrency:
    group: ports-release
    cancel-in-progress: false

jobs:
    release:
        permissions:
            contents: write
        uses: ./.github/workflows/release.yml
