local runs={}
for _,run in ipairs(require(script.Parent.DiscGoldenData1)) do table.insert(runs,run) end
for _,run in ipairs(require(script.Parent.DiscGoldenData2)) do table.insert(runs,run) end
for _,run in ipairs(require(script.Parent.DiscGoldenData3)) do table.insert(runs,run) end
for _,run in ipairs(require(script.Parent.DiscGoldenData4)) do table.insert(runs,run) end
for _,run in ipairs(require(script.Parent.DiscGoldenData5)) do table.insert(runs,run) end
for _,run in ipairs(require(script.Parent.DiscGoldenData6)) do table.insert(runs,run) end
for _,run in ipairs(require(script.Parent.DiscGoldenData7)) do table.insert(runs,run) end
for _,run in ipairs(require(script.Parent.DiscGoldenData8)) do table.insert(runs,run) end
for _,run in ipairs(require(script.Parent.DiscGoldenData9)) do table.insert(runs,run) end
for _,run in ipairs(require(script.Parent.DiscGoldenData10)) do table.insert(runs,run) end
return runs
