local runs={}
for _,r in ipairs(require(script.Parent.GhostGoldenData1)) do table.insert(runs,r) end
for _,r in ipairs(require(script.Parent.GhostGoldenData2)) do table.insert(runs,r) end
for _,r in ipairs(require(script.Parent.GhostGoldenData3)) do table.insert(runs,r) end
for _,r in ipairs(require(script.Parent.GhostGoldenData4)) do table.insert(runs,r) end
for _,r in ipairs(require(script.Parent.GhostGoldenData5)) do table.insert(runs,r) end
for _,r in ipairs(require(script.Parent.GhostGoldenData6)) do table.insert(runs,r) end
for _,r in ipairs(require(script.Parent.GhostGoldenData7)) do table.insert(runs,r) end
for _,r in ipairs(require(script.Parent.GhostGoldenData8)) do table.insert(runs,r) end
for _,r in ipairs(require(script.Parent.GhostGoldenData9)) do table.insert(runs,r) end
for _,r in ipairs(require(script.Parent.GhostGoldenData10)) do table.insert(runs,r) end
for _,r in ipairs(require(script.Parent.GhostGoldenData11)) do table.insert(runs,r) end
for _,r in ipairs(require(script.Parent.GhostGoldenData12)) do table.insert(runs,r) end
for _,r in ipairs(require(script.Parent.GhostGoldenData13)) do table.insert(runs,r) end
for _,r in ipairs(require(script.Parent.GhostGoldenData14)) do table.insert(runs,r) end
for _,r in ipairs(require(script.Parent.GhostGoldenData15)) do table.insert(runs,r) end
return runs
