local runs={}
for _,r in ipairs(require(script.Parent.SteamGoldenData1)) do table.insert(runs,r) end
for _,r in ipairs(require(script.Parent.SteamGoldenData2)) do table.insert(runs,r) end
for _,r in ipairs(require(script.Parent.SteamGoldenData3)) do table.insert(runs,r) end
for _,r in ipairs(require(script.Parent.SteamGoldenData4)) do table.insert(runs,r) end
for _,r in ipairs(require(script.Parent.SteamGoldenData5)) do table.insert(runs,r) end
for _,r in ipairs(require(script.Parent.SteamGoldenData6)) do table.insert(runs,r) end
for _,r in ipairs(require(script.Parent.SteamGoldenData7)) do table.insert(runs,r) end
for _,r in ipairs(require(script.Parent.SteamGoldenData8)) do table.insert(runs,r) end
for _,r in ipairs(require(script.Parent.SteamGoldenData9)) do table.insert(runs,r) end
for _,r in ipairs(require(script.Parent.SteamGoldenData10)) do table.insert(runs,r) end
for _,r in ipairs(require(script.Parent.SteamGoldenData11)) do table.insert(runs,r) end
for _,r in ipairs(require(script.Parent.SteamGoldenData12)) do table.insert(runs,r) end
for _,r in ipairs(require(script.Parent.SteamGoldenData13)) do table.insert(runs,r) end
for _,r in ipairs(require(script.Parent.SteamGoldenData14)) do table.insert(runs,r) end
for _,r in ipairs(require(script.Parent.SteamGoldenData15)) do table.insert(runs,r) end
return runs
